language: python
sudo: false
cache: false

matrix:
  include:
      # Only one test for these Python versions
      - env: ENV_FILE="ci/37-conda.yaml"

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info

  # free channel needed for older envs (< py37), see
  # https://github.com/conda/conda/issues/8849
  - conda config --set restore_free_channel true

  # Install dependencies
  - conda env create --file="${ENV_FILE}"
  - source activate test
  - if [ "$STYLE" ]; then pip install black flake8; fi
  - pip install -e .
  - conda list
  - python -c "import pandas;"

script:
  - pytest transx2gtfs --cov transx2gtfs -v --cov-report term-missing
  - if [ "$STYLE" ]; then black --check transx2gtfs; fi
  - if [ "$STYLE" ]; then flake8 transx2gtfs; fi

after_success:
  - codecov
