"""The GTFS tables produced for the fixtures must not change.

The TfL goldens were generated with the DOM-based implementation of 0.5.0 (and
regenerated deliberately when bank-holiday operation days and wait times were
implemented); the TXC 2.4/2.5 goldens were generated by this implementation and
reviewed by hand. They guard every later refactor. A large table is stored
zipped: python tests/regenerate_goldens.py rewrites them all."""

import pandas as pd
import pytest
from pandas.testing import assert_frame_equal

from transx2gtfs.agency import get_agency
from transx2gtfs.calendar import get_calendar
from transx2gtfs.calendar_dates import get_calendar_dates
from transx2gtfs.routes import get_routes
from transx2gtfs.stop_times import (
    drop_unresolved_stops,
    get_frequencies,
    get_stop_times,
)
from transx2gtfs.stops import get_stops
from transx2gtfs.transxchange import get_gtfs_info
from transx2gtfs.trips import get_trips
from transx2gtfs.txc import read_txc

from conftest import DATA_DIR, UNPACKED_DIR, txc24_fixture

TXC24 = {
    "SVRABAO001": "SVRABAO001.xml",
    "FWC001_FWAY_150": "FWC001_FWAY_150_PF000080424_20260901_20260714_210137.xml",
    "HRCS2_HRCS_240": "HRCS2_HRCS_240_PK20556564_20260831_20260730_114905.xml",
    "LGEN_403": "LGEN_403_LGENPK000181698403_20251025_-_2197827.xml",
}
FIXTURES = {
    "tfl_1-HAM-_-y05-2675925": UNPACKED_DIR / "tfl_1-HAM-_-y05-2675925.xml",
    "tfl_33-RB5-_-y05-7": UNPACKED_DIR / "tfl_33-RB5-_-y05-7.xml",
    "tfl_99-PIC-B-y05-4": UNPACKED_DIR / "tfl_99-PIC-B-y05-4.xml",
    **TXC24,
}


def read_fixture(name):
    source = FIXTURES[name]
    if name in TXC24:
        return read_txc(txc24_fixture(source), file_name=source)
    return read_txc(source)


TABLES = [
    "agency",
    "stops",
    "routes",
    "trips",
    "stop_times",
    "calendar",
    "calendar_dates",
    "frequencies",
]


def gtfs_tables(doc):
    """The tables as convert() builds them for one file"""
    stops = get_stops(doc)
    gtfs_info = drop_unresolved_stops(
        get_gtfs_info(doc), stops["stop_id"], doc.file_name
    )
    return {
        "agency": get_agency(doc),
        "stops": stops,
        "routes": get_routes(gtfs_info, doc),
        "trips": get_trips(gtfs_info),
        "stop_times": get_stop_times(gtfs_info),
        "calendar": get_calendar(gtfs_info),
        "calendar_dates": get_calendar_dates(gtfs_info),
        "frequencies": get_frequencies(gtfs_info),
    }


def read_golden(fixture, table):
    """A golden table: <table>.csv, or <table>.zip holding that CSV; None if absent"""
    directory = DATA_DIR / "golden" / fixture
    for candidate in (directory / (table + ".csv"), directory / (table + ".zip")):
        if candidate.exists():
            return pd.read_csv(candidate, dtype=str, keep_default_na=False)
    return None


@pytest.mark.parametrize("fixture", sorted(FIXTURES))
def test_gtfs_tables_match_golden(fixture):
    tables = gtfs_tables(read_fixture(fixture))
    for name in TABLES:
        expected = read_golden(fixture, name)
        if expected is None:
            # No golden file means the table was not produced (calendar_dates
            # without exceptions, frequencies without frequency journeys)
            assert tables[name] is None, name
            continue
        produced = tables[name].astype(str).reset_index(drop=True)
        assert_frame_equal(produced, expected, obj=name)
